[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
zkcash = "6JFJ27mebUcPSw1X5z5X6yKePQmuwQkusS7xNpE9kuUr"

[programs.devnet]
zkcash = "6JFJ27mebUcPSw1X5z5X6yKePQmuwQkusS7xNpE9kuUr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./deploy-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"

[package]
name = "zkcash"
version = "0.1.0"
description = "ZKCash program"
repository = "https://github.com/SocialfiPanda/zkcash"
