[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
zkcash = "F12PAMjHff2QHDwBTghE4BFzaaqNscKwno978La2vfQ5"

[programs.devnet]
zkcash = "BByY3XVe36QEn3omkkzZM7rst2mKqt4S4XMCrbM9oUTh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./deploy-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"

[package]
name = "zkcash"
version = "0.1.0"
description = "ZKCash program"
repository = "https://github.com/SocialfiPanda/zkcash"
